version: '3.8'

services:
  app:
    build: ./
    command: ./cmd
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    environment:
        - GONOSUMDB=off
        - TZ=Asia/Almaty
    depends_on:
      - postgres

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - .:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "dimash"
      POSTGRES_PASSWORD: "dimash"
      POSTGRES_DB: "OneLab"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5436:5432"
